# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapclientplugins\imagebasedfiducialmarkersstep\qt\imagebasedfiducialmarkerswidget.ui'
#
# Created: Tue Sep 11 14:37:18 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ImageBasedFiducialMarkersWidget(object):
    def setupUi(self, ImageBasedFiducialMarkersWidget):
        ImageBasedFiducialMarkersWidget.setObjectName("ImageBasedFiducialMarkersWidget")
        ImageBasedFiducialMarkersWidget.resize(870, 576)
        self.horizontalLayout = QtGui.QHBoxLayout(ImageBasedFiducialMarkersWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlPanel_groupBox = QtGui.QGroupBox(ImageBasedFiducialMarkersWidget)
        self.controlPanel_groupBox.setObjectName("controlPanel_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.controlPanel_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.time_groupBox.setObjectName("time_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.time_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timePlayStop_pushButton = QtGui.QPushButton(self.time_groupBox)
        self.timePlayStop_pushButton.setObjectName("timePlayStop_pushButton")
        self.gridLayout_4.addWidget(self.timePlayStop_pushButton, 1, 1, 1, 1)
        self.timeValue_label = QtGui.QLabel(self.time_groupBox)
        self.timeValue_label.setObjectName("timeValue_label")
        self.gridLayout_4.addWidget(self.timeValue_label, 0, 0, 1, 1)
        self.timeValue_doubleSpinBox = QtGui.QDoubleSpinBox(self.time_groupBox)
        self.timeValue_doubleSpinBox.setMaximum(12000.0)
        self.timeValue_doubleSpinBox.setObjectName("timeValue_doubleSpinBox")
        self.gridLayout_4.addWidget(self.timeValue_doubleSpinBox, 0, 1, 1, 1)
        self.timeLoop_checkBox = QtGui.QCheckBox(self.time_groupBox)
        self.timeLoop_checkBox.setObjectName("timeLoop_checkBox")
        self.gridLayout_4.addWidget(self.timeLoop_checkBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.time_groupBox)
        self.video_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.video_groupBox.setObjectName("video_groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.video_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameIndex_label = QtGui.QLabel(self.video_groupBox)
        self.frameIndex_label.setObjectName("frameIndex_label")
        self.gridLayout_2.addWidget(self.frameIndex_label, 0, 0, 1, 1)
        self.framesPerSecond_spinBox = QtGui.QSpinBox(self.video_groupBox)
        self.framesPerSecond_spinBox.setMinimum(1)
        self.framesPerSecond_spinBox.setProperty("value", 25)
        self.framesPerSecond_spinBox.setObjectName("framesPerSecond_spinBox")
        self.gridLayout_2.addWidget(self.framesPerSecond_spinBox, 1, 1, 1, 1)
        self.framesPerSecond_label = QtGui.QLabel(self.video_groupBox)
        self.framesPerSecond_label.setObjectName("framesPerSecond_label")
        self.gridLayout_2.addWidget(self.framesPerSecond_label, 1, 0, 1, 1)
        self.frameIndex_spinBox = QtGui.QSpinBox(self.video_groupBox)
        self.frameIndex_spinBox.setMinimum(1)
        self.frameIndex_spinBox.setMaximum(10000)
        self.frameIndex_spinBox.setObjectName("frameIndex_spinBox")
        self.gridLayout_2.addWidget(self.frameIndex_spinBox, 0, 1, 1, 1)
        self.numFrames_frame = QtGui.QFrame(self.video_groupBox)
        self.numFrames_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.numFrames_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.numFrames_frame.setObjectName("numFrames_frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.numFrames_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.numFrames_label = QtGui.QLabel(self.numFrames_frame)
        self.numFrames_label.setObjectName("numFrames_label")
        self.horizontalLayout_4.addWidget(self.numFrames_label)
        self.numFramesValue_label = QtGui.QLabel(self.numFrames_frame)
        self.numFramesValue_label.setObjectName("numFramesValue_label")
        self.horizontalLayout_4.addWidget(self.numFramesValue_label)
        self.gridLayout_2.addWidget(self.numFrames_frame, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.video_groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.defineROI_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.defineROI_radioButton.setChecked(True)
        self.defineROI_radioButton.setObjectName("defineROI_radioButton")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.defineROI_radioButton)
        self.defineROI_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.defineROI_pushButton.setObjectName("defineROI_pushButton")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.defineROI_pushButton)
        self.setInitialTrackingPoints_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.setInitialTrackingPoints_pushButton.setObjectName("setInitialTrackingPoints_pushButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.setInitialTrackingPoints_pushButton)
        self.setInitialTrackingPoints_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.setInitialTrackingPoints_radioButton.setObjectName("setInitialTrackingPoints_radioButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.setInitialTrackingPoints_radioButton)
        self.finaliseTrackingPoints_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.finaliseTrackingPoints_radioButton.setObjectName("finaliseTrackingPoints_radioButton")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.finaliseTrackingPoints_radioButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusText_label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusText_label.sizePolicy().hasHeightForWidth())
        self.statusText_label.setSizePolicy(sizePolicy)
        self.statusText_label.setObjectName("statusText_label")
        self.horizontalLayout_3.addWidget(self.statusText_label)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.done_pushButton = QtGui.QPushButton(self.frame)
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_2.addWidget(self.done_pushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.controlPanel_groupBox)
        self.sceneviewer_widget = BaseSceneviewerWidget(ImageBasedFiducialMarkersWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(ImageBasedFiducialMarkersWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageBasedFiducialMarkersWidget)

    def retranslateUi(self, ImageBasedFiducialMarkersWidget):
        ImageBasedFiducialMarkersWidget.setWindowTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Image Based Fiducial Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.controlPanel_groupBox.setTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.time_groupBox.setTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.timePlayStop_pushButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.timeValue_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Time value:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLoop_checkBox.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.video_groupBox.setTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Video:", None, QtGui.QApplication.UnicodeUTF8))
        self.frameIndex_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Frame index:", None, QtGui.QApplication.UnicodeUTF8))
        self.framesPerSecond_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Frames per second:", None, QtGui.QApplication.UnicodeUTF8))
        self.numFrames_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "# frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.numFramesValue_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Activity:", None, QtGui.QApplication.UnicodeUTF8))
        self.defineROI_radioButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Define ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.defineROI_pushButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Confirm", None, QtGui.QApplication.UnicodeUTF8))
        self.setInitialTrackingPoints_pushButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Confirm", None, QtGui.QApplication.UnicodeUTF8))
        self.setInitialTrackingPoints_radioButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Set initial tracking points", None, QtGui.QApplication.UnicodeUTF8))
        self.finaliseTrackingPoints_radioButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Finalise tracking points", None, QtGui.QApplication.UnicodeUTF8))
        self.statusText_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))


from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
